name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update stable
    - name: Build 
      working-directory: ./agent
      run: cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      working-directory: ./agent
      with:
        name: offensive_notion_linux_amd64 
        path: target/release/offensive_notion
      
  build_windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update stable
    - name: Build 
      working-directory: ./agent
      run: cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      working-directory: ./agent
      with:
        name: offensive_notion_win_64.exe
        path: target/release/offensive_notion.exe
